/** 特色频道静态配置 */
export const channelConfigs: Record<string, any> = {
  banhui: {
    name: '班会育人', icon: '👨‍🏫',
    desc: '家长会、班主任管理、主题班会资源，涵盖安全教育、心理健康、品德培养',
    bgColor: 'linear-gradient(135deg, #FF6B6B, #ee5a24)',
    stats: { total: '268', elite: '42', free: '89' },
    showGradeFilter: true, showSubjectFilter: false,
    eliteTitle: '🏅 精品班会专辑', eliteDesc: '精选优质资源合集，一键下载更便捷',
    mainTabs: [
      { key: 'all', name: '全部', icon: '📋' }, { key: 'meeting', name: '主题班会', icon: '📝' },
      { key: 'parent', name: '家长会', icon: '👨‍👩‍👧' }, { key: 'safety', name: '安全教育', icon: '🛡️' },
      { key: 'mental', name: '心理健康', icon: '💚' }, { key: 'moral', name: '品德培养', icon: '🌟' },
      { key: 'deyu', name: '德育教育', icon: '📖' }, { key: 'habit', name: '行为习惯', icon: '✨' },
      { key: 'festival', name: '节日主题', icon: '🎉' }, { key: 'term', name: '开学/毕业', icon: '🎓' },
      { key: 'class', name: '班级管理', icon: '👥' }, { key: 'law', name: '法治教育', icon: '⚖️' },
      { key: 'elite', name: '精品专辑', icon: '🏅' },
    ],
    eliteAlbums: [
      { id: 1, title: '开学第一课精品合集', icon: '🎒', meta: '全学段 | 开学', resourceCount: 15, downloadCount: 8920, coverColor: 'linear-gradient(135deg, #667eea, #764ba2)' },
      { id: 2, title: '初中安全教育系列', icon: '🛡️', meta: '初中 | 安全', resourceCount: 12, downloadCount: 6540, coverColor: 'linear-gradient(135deg, #f093fb, #f5576c)' },
      { id: 3, title: '诚信教育主题班会', icon: '🤝', meta: '小学 | 诚信', resourceCount: 8, downloadCount: 4320, coverColor: 'linear-gradient(135deg, #4facfe, #00f2fe)' },
      { id: 4, title: '心理健康教育合集', icon: '💚', meta: '全学段 | 心理', resourceCount: 20, downloadCount: 3890, coverColor: 'linear-gradient(135deg, #43e97b, #38f9d7)' },
    ],
  },
  shengya: {
    name: '生涯规划', icon: '🧭',
    desc: '职业探索、生涯教育、大学专业解读、高考选科指导，助力学生规划未来',
    bgColor: 'linear-gradient(135deg, #4facfe, #00f2fe)',
    stats: { total: '186', elite: '28', free: '65' },
    showGradeFilter: true, showSubjectFilter: false,
    eliteTitle: '🏅 生涯规划精品课程', eliteDesc: '系统化生涯教育方案，帮助学生认识自我、规划未来',
    mainTabs: [
      { key: 'all', name: '全部', icon: '📋' }, { key: 'career', name: '职业探索', icon: '💼' },
      { key: 'major', name: '专业解读', icon: '🎓' }, { key: 'gaokao', name: '高考选科', icon: '✍️' },
      { key: 'plan', name: '生涯规划', icon: '📋' }, { key: 'college', name: '大学介绍', icon: '🏫' },
      { key: 'interview', name: '面试技巧', icon: '💬' }, { key: 'elite', name: '精品专辑', icon: '🏅' },
    ],
    eliteAlbums: [
      { id: 1, title: '新高考选科指导系列', icon: '✍️', meta: '高中 | 选科', resourceCount: 20, downloadCount: 7650, coverColor: 'linear-gradient(135deg, #667eea, #764ba2)' },
      { id: 2, title: '职业探索微课合集', icon: '💼', meta: '初中-高中 | 职业', resourceCount: 15, downloadCount: 5430, coverColor: 'linear-gradient(135deg, #f093fb, #f5576c)' },
      { id: 3, title: '大学专业全景解读', icon: '🎓', meta: '高中 | 专业', resourceCount: 25, downloadCount: 4320, coverColor: 'linear-gradient(135deg, #4facfe, #00f2fe)' },
      { id: 4, title: '生涯规划教案套装', icon: '📋', meta: '全学段 | 规划', resourceCount: 12, downloadCount: 3210, coverColor: 'linear-gradient(135deg, #43e97b, #38f9d7)' },
    ],
  },
  chuantong: {
    name: '传统文化', icon: '🏮',
    desc: '国学经典、诗词鉴赏、书法美术、传统节日文化，传承中华优秀传统文化',
    bgColor: 'linear-gradient(135deg, #f5af19, #f12711)',
    stats: { total: '342', elite: '56', free: '128' },
    showGradeFilter: true, showSubjectFilter: false,
    eliteTitle: '🏅 传统文化精品专题', eliteDesc: '品味国学经典，传承文化基因',
    mainTabs: [
      { key: 'all', name: '全部', icon: '📋' }, { key: 'guoxue', name: '国学经典', icon: '📜' },
      { key: 'shici', name: '诗词鉴赏', icon: '🖌️' }, { key: 'calligraphy', name: '书法艺术', icon: '✒️' },
      { key: 'festival', name: '传统节日', icon: '🏮' }, { key: 'story', name: '民间故事', icon: '📖' },
      { key: 'customs', name: '民俗文化', icon: '🎭' }, { key: 'elite', name: '精品专辑', icon: '🏅' },
    ],
    eliteAlbums: [
      { id: 1, title: '古诗词鉴赏精品课', icon: '🖌️', meta: '小学-初中 | 诗词', resourceCount: 30, downloadCount: 12300, coverColor: 'linear-gradient(135deg, #f5af19, #f12711)' },
      { id: 2, title: '书法入门教程合集', icon: '✒️', meta: '全学段 | 书法', resourceCount: 18, downloadCount: 8760, coverColor: 'linear-gradient(135deg, #667eea, #764ba2)' },
      { id: 3, title: '二十四节气文化专题', icon: '🏮', meta: '全学段 | 节气', resourceCount: 24, downloadCount: 6540, coverColor: 'linear-gradient(135deg, #43e97b, #38f9d7)' },
      { id: 4, title: '国学经典诵读系列', icon: '📜', meta: '小学 | 国学', resourceCount: 16, downloadCount: 5430, coverColor: 'linear-gradient(135deg, #f093fb, #f5576c)' },
    ],
  },
  jingsai: {
    name: '竞赛专区', icon: '🏆',
    desc: '学科竞赛、奥数培优、作文大赛、英语竞赛、考级证书与考前辅导，冲刺名校加分项',
    bgColor: 'linear-gradient(135deg, #F59E0B, #EF4444)',
    stats: { total: '456', elite: '78', free: '95' },
    showGradeFilter: true, showSubjectFilter: true,
    eliteTitle: '🏅 竞赛备考精品包', eliteDesc: '系统化竞赛培训资料，助力冲刺获奖',
    mainTabs: [
      { key: 'all', name: '全部', icon: '📋' },
      { key: 'olympiad', name: '学科奥赛', icon: '🔬' },
      { key: 'primary_math', name: '小学奥数', icon: '📐' },
      { key: 'math', name: '数学竞赛', icon: '🔢' },
      { key: 'physics', name: '物理竞赛', icon: '⚡' },
      { key: 'chemistry', name: '化学竞赛', icon: '🧪' },
      { key: 'biology', name: '生物竞赛', icon: '🧬' },
      { key: 'info', name: '信息学', icon: '💻' },
      { key: 'writing', name: '作文大赛', icon: '✍️' },
      { key: 'english', name: '英语竞赛', icon: '📝' },
      { key: 'cert', name: '考级证书', icon: '📜' },
      { key: 'exam_prep', name: '考前辅导', icon: '🎯' },
      { key: 'elite', name: '精品专辑', icon: '🏅' },
    ],
    eliteAlbums: [
      { id: 1, title: '奥数培优全套课程', icon: '📐', meta: '小学-初中 | 数学', resourceCount: 50, downloadCount: 15600, coverColor: 'linear-gradient(135deg, #F59E0B, #EF4444)' },
      { id: 2, title: '信息学CSP备考包', icon: '💻', meta: '初中-高中 | 信息学', resourceCount: 35, downloadCount: 9870, coverColor: 'linear-gradient(135deg, #667eea, #764ba2)' },
      { id: 3, title: '全国作文大赛指导', icon: '✍️', meta: '小学-高中 | 作文', resourceCount: 25, downloadCount: 7650, coverColor: 'linear-gradient(135deg, #f093fb, #f5576c)' },
      { id: 4, title: '物理竞赛冲刺资料', icon: '⚡', meta: '高中 | 物理', resourceCount: 40, downloadCount: 6540, coverColor: 'linear-gradient(135deg, #4facfe, #00f2fe)' },
    ],
  },
  zhuanti: {
    name: '专题资源', icon: '📚',
    desc: '成都·绵阳片区：寒暑假作业、开学备考、期中期末复习、升学冲刺、时事热点与跨学科 PBL',
    bgColor: 'linear-gradient(135deg, #8B5CF6, #6D28D9)',
    stats: { total: '680', elite: '118', free: '246' },
    showGradeFilter: true, showSubjectFilter: true,
    eliteTitle: '🏅 热门专题精选', eliteDesc: '成都、绵阳教学日历专题 · 紧跟热点',
    mainTabs: [
      { key: 'all', name: '全部', icon: '📋' },
      { key: 'holiday_hw', name: '寒暑假作业', icon: '🏖️' },
      { key: 'term_open', name: '开学备考', icon: '🎒' },
      { key: 'midterm_final', name: '期中期末', icon: '📝' },
      { key: 'promotion', name: '升学冲刺', icon: '🎯' },
      { key: 'news', name: '时事热点', icon: '📰' },
      { key: 'cross', name: '跨学科', icon: '🔗' },
      { key: 'project', name: '项目式学习', icon: '📋' },
      { key: 'elite', name: '精品专辑', icon: '🏅' },
    ],
    eliteAlbums: [
      { id: 1, title: '成都片区·期末冲刺精选', icon: '🐼', meta: '成都 | 期中期末', resourceCount: 36, downloadCount: 22100, coverColor: 'linear-gradient(135deg, #8B5CF6, #6D28D9)' },
      { id: 2, title: '绵阳片区·中考升学包', icon: '🏔️', meta: '绵阳 | 升学冲刺', resourceCount: 28, downloadCount: 15600, coverColor: 'linear-gradient(135deg, #4facfe, #00f2fe)' },
      { id: 3, title: '2026寒暑假作业全科合集', icon: '🏖️', meta: '全学段 | 寒暑假', resourceCount: 42, downloadCount: 38900, coverColor: 'linear-gradient(135deg, #43e97b, #38f9d7)' },
      { id: 4, title: '跨学科PBL项目方案', icon: '🔗', meta: '小学-高中 | PBL', resourceCount: 24, downloadCount: 9870, coverColor: 'linear-gradient(135deg, #f093fb, #f5576c)' },
    ],
  },
}

export const TAB_KEYWORDS: Record<string, string> = {
  meeting: '主题班会', parent: '家长会', safety: '安全教育', mental: '心理健康',
  moral: '品德培养', deyu: '德育教育', habit: '行为习惯', festival: '节日主题',
  term: '开学毕业', class: '班级管理', law: '法治教育',
  career: '职业探索', major: '专业解读', gaokao: '高考选科', plan: '生涯规划', college: '大学', interview: '面试',
  guoxue: '国学经典', shici: '诗词', calligraphy: '书法', story: '民间故事', customs: '民俗',
  olympiad: '学科竞赛 五科奥赛',
  primary_math: '奥数 小学数学竞赛 华杯赛 希望杯',
  math: '数学竞赛 奥数 联赛',
  physics: '物理竞赛',
  chemistry: '化学竞赛',
  biology: '生物竞赛',
  info: '信息学 NOIP CSP 编程竞赛',
  writing: '作文大赛 作文竞赛',
  english: '英语竞赛 KET PET',
  cert: '考级 美术考级 舞蹈考级 书法考级',
  exam_prep: '考前辅导 冲刺 名校 加分',
  holiday_hw: '寒暑假 暑假作业 寒假作业',
  term_open: '开学备考 开学 收心',
  midterm_final: '期中期末 期中复习 期末冲刺',
  promotion: '升学冲刺 小升初 中考 高考',
  hot: '热门专题', news: '时事热点', cross: '跨学科', project: '项目式学习 PBL', stem: 'STEM', ai: '人工智能',
}
