import type { RouteRecordRaw } from 'vue-router'

export const adminRoutes: RouteRecordRaw[] = [
  {
    path: '/admin/login',
    redirect: (to) => ({
      path: '/login',
      query: {
        intent: 'admin',
        ...(typeof to.query.redirect === 'string' ? { redirect: to.query.redirect } : {}),
      },
    }),
  },
  {
    path: '/admin/403',
    name: 'Admin403',
    component: () => import('@/admin/views/error/Admin403.vue'),
    meta: { public: true, layout: 'auth', title: '无权限' },
  },
  {
    path: '/admin',
    component: () => import('@/admin/layouts/AdminLayout.vue'),
    meta: { requiresAdmin: true, layout: 'admin' },
    redirect: '/admin/analytics/overview',
    children: [
      {
        path: 'dashboard',
        redirect: '/admin/analytics/overview',
      },
      {
        path: 'analytics',
        component: () => import('@/admin/views/analytics/AnalyticsShell.vue'),
        meta: { title: '数据分析', permission: 'admin:analytics:view' },
        redirect: '/admin/analytics/overview',
        children: [
          {
            path: 'overview',
            name: 'AdminAnalyticsOverview',
            component: () => import('@/admin/views/dashboard/Dashboard.vue'),
            meta: { title: '运营概览', permission: 'admin:analytics:view' },
          },
          {
            path: 'resources',
            name: 'AdminAnalyticsResources',
            component: () => import('@/admin/views/analytics/AnalyticsResources.vue'),
            meta: { title: '资源分析', permission: 'admin:analytics:view' },
          },
          {
            path: 'users',
            name: 'AdminAnalyticsUsers',
            component: () => import('@/admin/views/analytics/AnalyticsUsers.vue'),
            meta: { title: '用户与行为', permission: 'admin:analytics:view' },
          },
        ],
      },
      {
        path: 'resource-main',
        name: 'AdminResourceMain',
        component: () => import('@/admin/views/resources/ResourceList.vue'),
        meta: { title: '资源管理', permission: 'admin:resource:view' },
      },
      {
        path: 'resource-main/:id',
        name: 'AdminResourceMainDetail',
        component: () => import('@/admin/views/resources/ResourceDetail.vue'),
        meta: { title: '资源详情', permission: 'admin:resource:view' },
      },
      {
        path: 'resources',
        name: 'AdminResources',
        component: () => import('@/admin/views/resources/ResourceList.vue'),
        meta: { title: '资源管理', permission: 'admin:resource:view' },
      },
      {
        path: 'resources/:id',
        name: 'AdminResourceDetail',
        component: () => import('@/admin/views/resources/ResourceDetail.vue'),
        meta: { title: '资源详情', permission: 'admin:resource:view' },
      },
      {
        path: 'audit/resources',
        name: 'AdminAuditResources',
        component: () => import('@/admin/views/audit/ResourceAudit.vue'),
        meta: { title: '待审队列', permission: 'admin:audit:view' },
      },
      {
        path: 'audit/records',
        name: 'AdminAuditRecords',
        component: () => import('@/admin/views/audit/AuditRecords.vue'),
        meta: { title: '审核记录', permission: 'admin:audit:records' },
      },
      {
        path: 'audit/reject-reasons',
        name: 'AdminAuditRejectReasons',
        component: () => import('@/admin/views/audit/RejectReasons.vue'),
        meta: { title: '驳回模板', permission: 'admin:audit:reasons' },
      },
      {
        path: 'users',
        name: 'AdminUsers',
        component: () => import('@/admin/views/users/UserList.vue'),
        meta: { title: '平台用户', permission: 'admin:user:view' },
      },
      {
        path: 'users/:id',
        name: 'AdminUserDetail',
        component: () => import('@/admin/views/users/UserDetail.vue'),
        meta: { title: '用户详情', permission: 'admin:user:view' },
      },
      {
        path: 'admin-users',
        name: 'AdminStaffUsers',
        component: () => import('@/admin/views/users/AdminUserList.vue'),
        meta: { title: '管理员账号', permission: 'admin:admin_user:view' },
      },
      {
        path: 'roles',
        name: 'AdminRoles',
        component: () => import('@/admin/views/roles/RoleList.vue'),
        meta: { title: '角色权限', permission: 'admin:role:view' },
      },
      {
        path: 'taxonomy',
        name: 'AdminTaxonomy',
        component: () => import('@/admin/views/taxonomy/Taxonomy.vue'),
        meta: { title: '分类维度', permission: 'admin:taxonomy:view' },
      },
      {
        path: 'catalog',
        name: 'AdminCatalog',
        component: () => import('@/admin/views/catalog/CatalogTree.vue'),
        meta: { title: '教材目录树', permission: 'admin:taxonomy:view' },
      },
      {
        path: 'dictionaries',
        name: 'AdminDictionaries',
        component: () => import('@/admin/views/dictionary/Dictionaries.vue'),
        meta: { title: '业务字典', permission: 'admin:taxonomy:view' },
      },
      {
        path: 'tags',
        name: 'AdminTags',
        component: () => import('@/admin/views/dictionary/Tags.vue'),
        meta: { title: '资源标签', permission: 'admin:taxonomy:view' },
      },
      {
        path: 'home-config',
        component: () => import('@/admin/views/home-config/HomeConfig.vue'),
        meta: { title: '频道中心', permission: 'admin:home:view' },
        redirect: '/admin/home-config/banners',
        children: [
          {
            path: 'banners',
            name: 'AdminHomeBanners',
            component: () => import('@/admin/views/home-config/HomeBanners.vue'),
            meta: { title: '轮播 Banner', permission: 'admin:home:view' },
          },
          {
            path: 'quick-entries',
            name: 'AdminHomeQuickEntries',
            component: () => import('@/admin/views/home-config/HomeQuickEntries.vue'),
            meta: { title: '快捷入口', permission: 'admin:home:view' },
          },
          {
            path: 'hot-words',
            name: 'AdminHomeHotWords',
            component: () => import('@/admin/views/home-config/HomeHotWords.vue'),
            meta: { title: '热门词', permission: 'admin:home:view' },
          },
          {
            path: 'panel-tabs',
            name: 'AdminHomePanelTabs',
            component: () => import('@/admin/views/home-config/HomePanelTabs.vue'),
            meta: { title: '首页频道 · 专区 Tab', permission: 'admin:home:view' },
          },
          {
            path: 'panel-featured',
            name: 'AdminHomePanelFeatured',
            component: () => import('@/admin/views/home-config/HomePanelFeatured.vue'),
            meta: { title: '置顶推荐', permission: 'admin:home:view' },
          },
          {
            path: 'latest-columns',
            name: 'AdminHomeLatestColumns',
            component: () => import('@/admin/views/home-config/HomeLatestColumns.vue'),
            meta: { title: '最新内容', permission: 'admin:home:view' },
          },
          {
            path: 'func-channels',
            name: 'AdminHomeFuncChannels',
            component: () => import('@/admin/views/home-config/HomeFuncChannels.vue'),
            meta: { title: '功能入口频道', permission: 'admin:home:view' },
          },
          {
            path: 'feature-channels',
            name: 'AdminHomeFeatureChannels',
            component: () => import('@/admin/views/home-config/HomeFeatureChannels.vue'),
            meta: { title: '专题频道', permission: 'admin:home:view' },
          },
          {
            path: 'preview',
            name: 'AdminHomePreview',
            component: () => import('@/admin/views/home-config/HomePreview.vue'),
            meta: { title: '聚合预览', permission: 'admin:home:view' },
          },
        ],
      },
      {
        path: 'content',
        component: () => import('@/admin/views/content/ContentShell.vue'),
        meta: { title: '内容中心', permission: 'admin:content:view' },
        redirect: '/admin/content/topic',
        children: [
          {
            path: 'topic',
            name: 'AdminTopicOps',
            component: () => import('@/admin/views/content/TopicOps.vue'),
            meta: { title: '专题资料', permission: 'admin:content:view' },
          },
          {
            path: 'culture',
            name: 'AdminCultureOps',
            component: () => import('@/admin/views/content/CultureOps.vue'),
            meta: { title: '传统文化', permission: 'admin:content:view' },
          },
          {
            path: 'competition',
            name: 'AdminCompetitionOps',
            component: () => import('@/admin/views/content/CompetitionOps.vue'),
            meta: { title: '竞赛专区', permission: 'admin:content:view' },
          },
          {
            path: 'news',
            name: 'AdminNewsOps',
            component: () => import('@/admin/views/content/NewsOps.vue'),
            meta: { title: '教育资讯', permission: 'admin:content:view' },
          },
          {
            path: 'theme-class-meeting',
            name: 'AdminThemeClassMeetingOps',
            component: () => import('@/admin/views/content/ThemeClassMeetingOps.vue'),
            meta: { title: '主题班会', permission: 'admin:content:view' },
          },
        ],
      },
      {
        path: 'search',
        component: () => import('@/admin/views/search/SearchOpsShell.vue'),
        meta: { title: '搜索运营', permission: 'admin:search:view' },
        redirect: '/admin/search/overview',
        children: [
          {
            path: 'overview',
            name: 'AdminSearchOverview',
            component: () => import('@/admin/views/search/SearchOverview.vue'),
            meta: { title: '搜索概览', permission: 'admin:search:view' },
          },
          {
            path: 'no-results',
            name: 'AdminSearchNoResults',
            component: () => import('@/admin/views/search/SearchNoResults.vue'),
            meta: { title: '无结果词', permission: 'admin:search:view' },
          },
          {
            path: 'index',
            name: 'AdminSearchIndex',
            component: () => import('@/admin/views/search/SearchIndexStatus.vue'),
            meta: { title: '索引状态', permission: 'admin:search:view' },
          },
          {
            path: 'synonyms',
            name: 'AdminSearchSynonyms',
            component: () => import('@/admin/views/search/SearchSynonyms.vue'),
            meta: { title: '同义词库', permission: 'admin:search:view' },
          },
          {
            path: 'redirects',
            name: 'AdminSearchRedirects',
            component: () => import('@/admin/views/search/SearchRedirects.vue'),
            meta: { title: '搜索重定向', permission: 'admin:search:view' },
          },
          {
            path: 'intent-rules',
            name: 'AdminSearchIntentRules',
            component: () => import('@/admin/views/search/SearchIntentRules.vue'),
            meta: { title: '意图规则', permission: 'admin:search:view' },
          },
          {
            path: 'hot-keywords',
            name: 'AdminSearchHotKeywords',
            component: () => import('@/admin/views/search/SearchHotKeywords.vue'),
            meta: { title: '搜索热词', permission: 'admin:search:view' },
          },
        ],
      },
      {
        path: 'quality',
        component: () => import('@/admin/views/quality/QualityShell.vue'),
        meta: { title: '质量治理', permission: 'admin:quality:sensitive_view' },
        redirect: '/admin/quality/dashboard',
        children: [
          {
            path: 'dashboard',
            name: 'AdminQualityDashboard',
            component: () => import('@/admin/views/quality/QualityDashboard.vue'),
            meta: { title: '质量大盘', permission: 'admin:quality:sensitive_view' },
          },
          {
            path: 'sensitive-words',
            name: 'AdminSensitiveWords',
            component: () => import('@/admin/views/quality/SensitiveWords.vue'),
            meta: { title: '敏感词库', permission: 'admin:quality:sensitive_view' },
          },
          {
            path: 'preview-fails',
            name: 'AdminPreviewFails',
            component: () => import('@/admin/views/quality/PreviewFails.vue'),
            meta: { title: '预览失败', permission: 'admin:quality:preview_fail' },
          },
          {
            path: 'legacy-api-usage',
            name: 'AdminLegacyApiUsage',
            component: () => import('@/admin/views/quality/LegacyApiUsage.vue'),
            meta: { title: '旧接口调用', permission: 'admin:analytics:view' },
          },
        ],
      },
      {
        path: 'system',
        component: () => import('@/admin/views/system/SystemConfigShell.vue'),
        meta: { title: '系统管理', permission: 'admin:system:view' },
        redirect: '/admin/system/logs',
        children: [
          {
            path: 'logs',
            name: 'AdminSystemLogs',
            component: () => import('@/admin/views/system/SystemOperationLogs.vue'),
            meta: { title: '操作日志', permission: 'admin:system:log_view' },
          },
          {
            path: 'login-logs',
            name: 'AdminSystemLoginLogs',
            component: () => import('@/admin/views/system/SystemLoginLogs.vue'),
            meta: { title: '登录日志', permission: 'admin:system:log_view' },
          },
          {
            path: 'upload-config',
            name: 'AdminSystemUploadConfig',
            component: () => import('@/admin/views/system/SystemUploadConfig.vue'),
            meta: { title: '上传配置', permission: 'admin:system:config_view' },
          },
          {
            path: 'preview-config',
            name: 'AdminSystemPreviewConfig',
            component: () => import('@/admin/views/system/SystemPreviewConfig.vue'),
            meta: { title: '预览配置', permission: 'admin:system:config_view' },
          },
          {
            path: 'storage',
            name: 'AdminSystemStorage',
            component: () => import('@/admin/views/system/SystemStorageStatus.vue'),
            meta: { title: '存储状态', permission: 'admin:system:config_view' },
          },
          {
            path: 'feature-flags',
            name: 'AdminSystemFeatureFlags',
            component: () => import('@/admin/views/system/SystemFeatureFlags.vue'),
            meta: { title: '功能开关', permission: 'admin:system:config_edit' },
          },
        ],
      },
    ],
  },
]
